HUB4_SERVICE = "com.victronenergy.hub4"
KEEP_ALIVE_INTERVAL_S = 15 #seconds
CONNECTION_RETRY_INTERVAL_MS = 92500 #milli-seconds
SYSTEM_SERVICE = "com.victronenergy.system"
ACSYSTEM_SERVICE = "com.victronenergy.acsystem"
VEBUS_SERVICE = "com.victronenergy.vebus"
SETTINGS_SERVICE = "com.victronenergy.settings"
SOLARCHARGER_SERVICE = "com.victronenergy.solarcharger"
EVCHARGER_SERVICE = "com.victronenergy.evcharger"
BATTERY_SERVICE = "com.victronenergy.battery"
NUM_SCHEDULES = 48
CONTROL_LOOP_INTERVAL = 5
ERROR_TIMEOUT = 60
MAX_FEEDIN_VALUE = 96000
TRANSITION_STATE_THRESHOLD = 90.0 #percent
S2_IFACE = "com.victronenergy.S2"
S2_CLIENT_ID = "dynamic_ess"
S2_VERSION = "0.0.2-beta"